apiVersion: v1
kind: Service
metadata:
  name: biniyam-seid-service
  namespace: biniyam-seid-development
  annotations:
    author: "Biniyam Seid - UGR-9483-13"
    description: "Service for Biniyam Seid's application"
    created-by: "Biniyam Seid"
    student-id: "UGR-9483-13"
    hostname: "divinecodecompiler"
  labels:
    app: biniyam-seid-app
    student: biniyam-seid
    environment: development
spec:
  selector:
    app: biniyam-seid-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  type: ClusterIP 