apiVersion: v1
kind: ConfigMap
metadata:
  name: biniyam-seid-config
  namespace: biniyam-seid-development
  annotations:
    author: "Biniyam Seid - UGR-9483-13"
    description: "Configuration data for Biniyam Seid's Kubernetes lab"
    created-by: "Biniyam Seid"
    student-id: "UGR-9483-13"
    hostname: "divinecodecompiler"
  labels:
    app: biniyam-seid-app
    student: biniyam-seid
    environment: development
data:
  student.name: "Biniyam Seid"
  student.id: "UGR-9483-13"
  hostname: "divinecodecompiler"
  environment: "development"
  lab.title: "Kubernetes Lab Exercise"
  created.date: "2024"
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Biniyam Seid - Kubernetes Lab</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; background-color: #f0f0f0; }
            .container { background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .header { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
            .info { margin: 20px 0; }
            .label { font-weight: bold; color: #34495e; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1 class="header">Kubernetes Lab Exercise</h1>
            <div class="info">
                <p><span class="label">Student Name:</span> Biniyam Seid</p>
                <p><span class="label">Student ID:</span> UGR-9483-13</p>
                <p><span class="label">Hostname:</span> divinecodecompiler</p>
                <p><span class="label">Environment:</span> Development</p>
                <p><span class="label">Namespace:</span> biniyam-seid-development</p>
            </div>
            <p>This application is running in a Kubernetes cluster as part of a lab exercise.</p>
        </div>
    </body>
    </html> 